--liquibase formatted sql

--changeset zlatovchena:1
--comment: create users table
CREATE table if not exists users
(
    id       bigint generated by default as identity primary key,
    login    varchar(255) not null unique,
    password varchar(255) not null
);

--changeset zlatovchena:2
--comment: create users_profiles table
CREATE TABLE user_profiles
(
    id          bigint generated by default as identity primary key,
    user_id     bigint      NOT NULL unique,
    name        VARCHAR(50) NOT NULL,
    age         INTEGER     NOT NULL,
    photo       TEXT,
    city        VARCHAR(50),
    height      INTEGER,
    zodiac_sign VARCHAR(20),
    FOREIGN KEY (user_id) REFERENCES users (id)
);

--changeset zlatovchena:3
--comment: create users_contacts table
CREATE TABLE user_contacts
(
    id           bigint generated by default as identity primary key,
    user_id      bigint NOT NULL unique,
    telegram     VARCHAR(50) CHECK (telegram LIKE '@%'),
    phone_number VARCHAR(11) CHECK (phone_number ~ '^[0-9]{11}$'),
    FOREIGN KEY (user_id) REFERENCES users (id)
);
